// Generated by scripts/build.py - do not edit by hand.
// Last build: 2026-08-03 16:55 UTC
const PROGRAMS = {
  "general": {
    "label": "General",
    "name": "General",
    "color": "#205493"
  },
  "bta": {
    "label": "BTA",
    "name": "BTA",
    "color": "#007834"
  },
  "hhb": {
    "label": "HHB",
    "name": "HHB",
    "color": "#6e2c8e"
  }
};
const SESSIONS = [
  {
    "date": "2026-08-04",
    "program": "general",
    "title": "Test Event 1",
    "meta": "All day \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  },
  {
    "date": "2026-08-05",
    "program": "general",
    "title": "Test Event 2",
    "meta": "All day \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  },
  {
    "date": "2026-08-11",
    "program": "bta",
    "title": "Test BTA Training",
    "meta": "9:00 a.m. - 9:30 a.m. \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  },
  {
    "date": "2026-09-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-10-07",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Tool Kit Workshop: SU/SD, School, and Educator",
    "meta": "9:00 a.m. - 12:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees, educators \u00b7 Ashley Riendeau and Monica Desrochers",
    "action": "reg",
    "url": "https://forms.cloud.microsoft/pages/responsepage.aspx?id=O5O0IK26PEOcAnDtzHVZxrCjEi6hGPtEnXtYvzFVNH9UQUhQUDFXTjhIV0NLSTc2RlVHUjZaRTVUUC4u&route=shorturl",
    "linkText": "Register"
  },
  {
    "date": "2026-10-19",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-11-16",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-12-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-01-18",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-02-15",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-03-15",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-04-19",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-05-17",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-06-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual \u00b7 School/district administrators and designees \u00b7 Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  }
];
