// Generated by scripts/build.py - do not edit by hand.
// Last build: 2026-08-03 16:21 UTC
const PROGRAMS = {
  "general": {
    "label": "General",
    "name": "General",
    "color": "#205493"
  }
};
const SESSIONS = [
  {
    "date": "2026-08-04",
    "program": "general",
    "title": "Test Event 1",
    "meta": "All day \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  },
  {
    "date": "2026-08-05",
    "program": "general",
    "title": "Test Event 2",
    "meta": "All day \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  },
  {
    "date": "2026-08-11",
    "program": "general",
    "title": "Test BTA Training",
    "meta": "9:00 a.m. - 9:30 a.m. \u00b7 Virtual",
    "action": "none",
    "noteText": ""
  }
];
