// Generated by scripts/build.py - do not edit by hand.
// Last build: 2026-09-02 09:29 UTC
const PROGRAMS = {
  "mckinney-vento": {
    "label": "McKinney-Vento",
    "name": "McKinney-Vento",
    "color": "#00629b"
  },
  "foster-care": {
    "label": "Foster Care",
    "name": "Foster Care",
    "color": "#4d5d2c"
  },
  "rule-4500": {
    "label": "Rule 4500",
    "name": "Rule 4500",
    "color": "#9c3d00"
  },
  "universal-screening": {
    "label": "Universal Screening",
    "name": "Universal Screening",
    "color": "#8a1e41"
  },
  "hhb": {
    "label": "HHB",
    "name": "HHB",
    "color": "#6e2c8e"
  },
  "bta": {
    "label": "BTA",
    "name": "BTA",
    "color": "#007834"
  },
  "discipline": {
    "label": "Discipline",
    "name": "Discipline",
    "color": "#00575c"
  }
};
const SESSIONS = [
  {
    "date": "2026-08-10",
    "program": "mckinney-vento",
    "title": "McKinney-Vento 101",
    "meta": "11:00 a.m. - 12:00 p.m. \u00b7 Virtual",
    "audience": "Local homeless liaisons, administrators, home-school coordinators, community school coordinators, registrars",
    "provider": "Kate Paxton, State Program Coordinator for Homeless Children and Youth",
    "action": "details",
    "url": "https://education.vermont.gov/student-support/federal-programs/consolidated-federal-programs/education-homeless-children-and",
    "linkText": "More information"
  },
  {
    "date": "2026-08-20",
    "program": "foster-care",
    "title": "Educational Stability / Best Interest Determination for Students in Foster Care",
    "meta": "1:00 p.m. - 3:00 p.m. \u00b7 Virtual",
    "audience": "Principals and special education administrators, DCF workers",
    "provider": "Alicia Hanrahan (AOE) and Barbara Joyal (DCF)",
    "action": "none",
    "noteText": "No registration needed"
  },
  {
    "date": "2026-09-09",
    "program": "rule-4500",
    "title": "Rule 4500 Overview",
    "meta": "12:30 p.m. - 2:30 p.m. \u00b7 Virtual",
    "audience": "Administrators, special education directors, crisis response teams, and other school personnel",
    "provider": "Ashley Riendeau",
    "action": "none",
    "noteText": "Registration coming summer 2026"
  },
  {
    "date": "2026-09-10",
    "program": "universal-screening",
    "title": "Universal Screening 101: Building the Foundations of a Social, Emotional, and Behavioral Data System",
    "meta": "10:00 a.m. - 11:00 a.m. \u00b7 Virtual",
    "audience": "MTSS coordinators, administrators, student support services directors, school counselors and clinicians, teacher leaders",
    "provider": "Kate Paxton (AOE) and Marianna Donnally (DMH)",
    "action": "details",
    "url": "https://education.vermont.gov/sites/aoe/files/documents/edu-universal-screening-for-social-emotional-behavioral-needs-and-strengths-in-vt-schools.pdf",
    "linkText": "More information"
  },
  {
    "date": "2026-09-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-10-05",
    "program": "bta",
    "title": "Behavioral Threat Assessment Training Level I",
    "meta": "8:00 a.m. - 3:00 p.m. \u00b7 Virtual",
    "audience": "BTA team members, administrators, school safety leads",
    "provider": "Safe & Sound Schools",
    "action": "reg",
    "url": "https://safeandsound.swoogo.com/BTA-Annual-Training-2026",
    "linkText": "Register"
  },
  {
    "date": "2026-10-05",
    "program": "discipline",
    "title": "Exclusionary Discipline Guidance Overview Training",
    "meta": "9:00 a.m. - 11:00 a.m. \u00b7 Virtual",
    "audience": "District/SU and school administrators",
    "provider": "Ashley Riendeau",
    "action": "none",
    "noteText": "Registration coming summer 2026"
  },
  {
    "date": "2026-10-07",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Tool Kit Workshop: SU/SD, School, and Educator",
    "meta": "9:00 a.m. - 12:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees, educators",
    "provider": "Ashley Riendeau and Monica Desrochers",
    "action": "reg",
    "url": "https://forms.cloud.microsoft/pages/responsepage.aspx?id=O5O0IK26PEOcAnDtzHVZxrCjEi6hGPtEnXtYvzFVNH9UQUhQUDFXTjhIV0NLSTc2RlVHUjZaRTVUUC4u&route=shorturl",
    "linkText": "Register"
  },
  {
    "date": "2026-10-19",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-11-16",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2026-12-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-01-18",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-02-15",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-03-15",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-04-19",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-05-17",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  },
  {
    "date": "2027-06-21",
    "program": "hhb",
    "title": "Harassment, Hazing and Bullying (HHB) Office Hours",
    "meta": "1:00 p.m. - 2:00 p.m. \u00b7 Virtual",
    "audience": "School/district administrators and designees",
    "provider": "Monica Desrochers and Ashley Riendeau",
    "action": "reg",
    "url": "https://education.vermont.gov",
    "linkText": "Join the session",
    "noteText": "No registration needed - drop in"
  }
];
